[package]
name = "catenary-backend"
version = "0.1.1"
edition = "2021"
description = "import and backend for gtfs data"
license-file = "LICENSE"

[lints.rust]
unused_must_use = "deny"
non_ascii_idents = "deny"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
crossbeam-utils = "0.8.16"
memoffset = "0.9.0"
time = "0.3.30"
rouille = "3.0"
#gtfs-rt = {git = "https://github.com/lolpro11/gtfs-rt"}
gtfs-rt = "0.4"
reqwest = {version = "0.11", default-features = false, features = ["gzip","brotli","rustls-tls","deflate"]}
protobuf = "3.3"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.33", features = ["full"] }
futures = "0.3"
#gtfs-structures = { git = "https://github.com/lolpro11/gtfs-structure"}
gtfs-structures = "0.41"
tungstenite = "0.21.0"
postgres = "0.19.7"
postgis = "0.9.0"
arguments = "0.7.2"
tokio-postgres = { version = "0.7.10", features = [
    "array-impls",
    "with-geo-types-0_7",
] }
rust_decimal = "1.32.0"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio-rustls"] }
serde_json = "1.0.107"
actix-web = { version = "4.4.1", default-features = false, features =  ["compress-brotli", "compress-gzip", "http2"] }
regress = "0.9.0"
color-eyre = {version = "0.6.2", features = ["url", "issue-url"]}
rgb = "0.8.36"
clap = {version = "4.4.7", features = ["derive"]}
itertools = "0.12.0"
fs_extra = "1.3.0"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.1"
bb8-postgres = "0.8.1"
bb8 = "0.8.1"
threadpool = {version = "1.8.1"}
tokio-threadpool = "0.1.18"
qstring = "0.7.2"
rand = "0.8.5"
titlecase = "2.2.1"
rayon = "1.8.0"
chrono = "0.4.31"
geo-types = "0.7.11"
geo-postgis = "0.2.2"
geo = "0.28.0"
tarpc = {version = "0.33.0", features = ["full"]}
anyhow = "1.0.75"
tracing = "0.1.40"
service = "0.0.0"
tokio-serde = "0.9.0"
tracing-subscriber = "0.3.17"
futures-util = "0.3.29"
#actix_block_ai_crawling = "0.2.8"
kactus = "0.1.0"
actix = "0.13.1"
actix-web-actors = "4.2.0"
amtk = "0.1.0"
geojson = "0.24.1"
travelling_salesman = "1.1.22"
ordered-float = "4.2.0"

[[bin]]
name = "http_server"
path = "src/http-server.rs"

[[bin]]
name = "transitlanddownload"
path = "src/ingest_gtfs_schedule/from-transitland.rs"

[[bin]]
name = "import"
path = "src/ingest_gtfs_schedule/main.rs"

[[bin]]
name = "move_to_prod"
path = "src/ingest_gtfs_schedule/move_to_prod.rs"

[[bin]]
name = "update_functions"
path = "src/ingest_gtfs_schedule/update_functions.rs"

[[bin]]
name = "importnopostgres"
path = "src/ingest_gtfs_schedule/nopostgres.rs"

[[bin]]
name = "flattenuncompressed"
path = "src/ingest_gtfs_schedule/flatten.rs"

[[bin]]
name = "newunzip"
path = "src/ingest_gtfs_schedule/new-unzip.rs"

[[bin]]
name = "aspen"
path = "src/aspen/main.rs"

[lib]
name = "aspenlib"
path = "src/aspen/lib.rs"

[[bin]]
name = "spruce"
path = "src/spruce/main.rs"

[features]
#![feature(async_closure)]

#[target.'cfg(target_os = "linux")']
#rustflags = ["-C", "target-feature=+crt-static"]
